apiVersion: v1
kind: Service
metadata:
  name: redis-follower
  namespace: cap1463-09  # CAMBIO: Namespace añadido.
  labels:
    app: redis
    role: follower
    tier: backend
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: follower
    tier: backend