apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  # CAMBIO: Namespace obligatorio para que el servicio encuentre los pods en el entorno.
  namespace: cap1463-09
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: leader
    tier: backend